name: Run Gradle Task

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run (e.g., iosSimulatorArm64)'
        required: true
        type: string

jobs:
  run-gradle:
    runs-on: macos-15
    timeout-minutes: 60

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set project key
        id: pj-key
        run: |
          echo "KOTLIN_VERSION=$(grep "^kotlin =" gradle/libs.versions.toml | awk -F '=' '{print $2}' | tr -d ' "')" >> $GITHUB_OUTPUT

      - name: Setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Cache konan
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          # ref. https://kotlinlang.org/docs/native-improving-compilation-time.html#preserve-downloaded-and-cached-components-between-builds
          path: ~/.konan
          key: v1-${{ runner.os }}-konan-${{ steps.pj-key.outputs.KOTLIN_VERSION }}

      - name: Set Xcode version
        # ref. https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html#version-compatibility
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Run task on macos
        run: ./gradlew ${{ github.event.inputs.task }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: reports-build
          path: |
            **/build/reports/**
          retention-days: 5
