name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "art/**"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ macos-15, ubuntu-latest ]
        job: [ test ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set project key
        id: pj-key
        run: |
          echo "KOTLIN_VERSION=$(grep "^kotlin =" gradle/libs.versions.toml | awk -F '=' '{print $2}' | tr -d ' "')" >> $GITHUB_OUTPUT
      - name: Copy CI gradle.properties
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Cache konan
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          # ref. https://kotlinlang.org/docs/native-improving-compilation-time.html#preserve-downloaded-and-cached-components-between-builds
          path: ~/.konan
          key: v1-${{ runner.os }}-konan-${{ steps.pj-key.outputs.KOTLIN_VERSION }}

      # macos-15
      - name: Set Xcode version
        if: matrix.os == 'macos-15' && matrix.job == 'test'
        # ref. https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html#version-compatibility
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Run tests on macos
        if: matrix.os == 'macos-15' && matrix.job == 'test'
        run: ./gradlew iosSimulatorArm64Test

      # ubuntu-latest
      - name: Run tests on linux
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: ./gradlew testDebugUnitTest desktopTest wasmJsTest jsTest

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: reports-build
          path: |
            **/build/reports/**
          retention-days: 5
